name: Ebay Data Scraper

on:
  schedule:
    - cron: "0 */3 * * *"  # Runs every 3 hours
  workflow_dispatch:

jobs:
  scrape-bitcoin:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # Avoid overwriting token

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium pandas webdriver-manager fake-useragent

      - name: Run Selenium scraper
        run: python scraper.py

      - name: Commit and push updated CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Ensure we’re on main and clean
          git fetch origin main
          git checkout main
          git reset --hard origin/main

          git add ebay_tech_deals.csv
          git commit -m "Updated Ebay data (3-hour intervals)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
