name: eBay Tech Deals Scraper

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run scraper
        run: python scraper.py

      - name: Commit & push CSV
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add bitcoin_hourly_data.csv
          git commit -m "Updated Bitcoin data (10-min intervals)"
          git push
